ALTER TABLE "Party"
ADD COLUMN "portalLat" DOUBLE PRECISION NOT NULL DEFAULT 43.090003,
ADD COLUMN "portalLng" DOUBLE PRECISION NOT NULL DEFAULT -79.068051,
ADD COLUMN "portalIsPublic" BOOLEAN NOT NULL DEFAULT true;
