[build]
target = "index.html"
dist = "../backend/static/play"
public_url = "/play/"

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:4000/api/"

[[proxy]]
rewrite = "/ws"
backend = "ws://127.0.0.1:4000/ws"
ws = true
